openapi: 3.0.1
info:
  title: Faculty Of Computing And Informatics
  version: 5.4.0
servers:
- url: "{server}:{port}/Faculty_of_Computing_and_Informatics"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /addCourse:
    post:
      operationId: postAddcourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturers'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /getAllCourses:
    get:
      operationId: getGetallcourses
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
  /getAllLecturers:
    get:
      operationId: getGetalllecturers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturers'
  /updateCourse:
    put:
      operationId: putUpdatecourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /updateLecturer:
    put:
      operationId: putUpdatelecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturers'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /getCoursebyCoursecode:
    get:
      operationId: getGetcoursebycoursecode
      parameters:
      - name: Course_code
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            text/plain:
              schema:
                type: string
  /getLecturerbyStaffnumber:
    get:
      operationId: getGetlecturerbystaffnumber
      parameters:
      - name: Staff_number
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturers'
            text/plain:
              schema:
                type: string
  /deleteCourse:
    delete:
      operationId: deleteDeletecourse
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /deleteLecturer:
    delete:
      operationId: deleteDeletelecturer
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Lecturers:
      required:
      - Age
      - Email
      - First_course
      - Gender
      - Name
      - Office_number
      - Second_course
      - Staff_number
      - Surname
      - Third_course
      - Title
      type: object
      properties:
        Staff_number:
          type: string
        Title:
          type: string
        Name:
          type: string
        Surname:
          type: string
        Age:
          type: string
        Gender:
          type: string
        Office_number:
          type: string
        First_course:
          type: string
        Second_course:
          type: string
        Third_course:
          type: string
        Email:
          type: string
    Course:
      required:
      - Course_code
      - NQF_level
      - Name
      type: object
      properties:
        Course_code:
          type: string
        Name:
          type: string
        NQF_level:
          type: string
